on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: install & build
        shell: bash
        run: |
          yarn install --network-concurrency 1
          cp public/config/gh-pages.js public/config/local.js
          BASE_PATH=/maperture/ yarn build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
      - name: cleanup
        shell: bash
        run: |
          rm public/config/local.js
