on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: install
        run: yarn install --network-concurrency 1
      - name: build & deploy
        run: BASE_PATH=/maperture/ yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
